source "https://rubygems.org"

# commented the line below to get rid of github authentication warnings
# gem "github-pages", group: :jekyll_plugins

# added the following line, same reason as above
gem "jekyll", ">= 4.0.0", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap", ">= 1.3.0"
  gem "jekyll-gist"
  gem "jekyll-feed", ">= 0.12.0"
  gem "jemoji", ">= 0.11.0"
#  gem "jekyll-asciidoc" # this doesn't work yet, since it's blacklisted on Github :-( We use Gradle Asciidoctor for now...
end
